apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: udagram-api-feed
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: udagram-api-feed
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 20