apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: simple-node
        image: letrung1998vn/udagram-api-feed:v1
        ports:
        - containerPort: 8080